apiVersion: helix.ml/v1alpha1
kind: Project
metadata:
  name: robot-hq
spec:
  description: "Full-stack web application"
  technologies: [React, Go, PostgreSQL]
  guidelines: |
    Use conventional commits. All PRs require tests.
  repository:
    url: "https://github.com/binocarlos/robot-hq"
    branch: main
  startup:
    install: "docker compose build"
    start:   "docker compose up -d"
  kanban:
    wip_limits:
      planning:       5      # 0 = unlimited
      implementation: 3
      review:         3
  tasks:
    - title: "Add a second real-time graph to the home page"
      description: "On the home screen there is currently a single real-time graph which shows telemetry for our robots.  Can we have a second real-time telemetry graph that shows the current emotional breakdown distribution?"
    - title: "Add tests for the API"
      description: "We currently don't test the API at all - please add a test suite and hook up github actions to run those tests on every push"
  agent:
    name: "Project Assistant"
    model: claude-opus-4-6
    provider: anthropic
    system_prompt: |
      You are a coding assistant for this project.
    tools:
      web_search: true
      browser: false
